axonweb3/axon-devops

- k8s-deploy/k8s/axon/axon-chain.yaml
- k8s-deploy/k8s/axon/axon1-deployment.yaml
- k8s-deploy/k8s/axon/axon2-deployment.yaml
- k8s-deploy/k8s/axon/axon3-deployment.yaml
- k8s-deploy/k8s/axon/axon4-deployment.yaml
feat: nginx proxy axon rpc request
> feat: nginx proxy axon rpc request

- k8s-deploy/k8s/axon/axon1-statefulset.yaml
- k8s-deploy/k8s/axon/axon2-statefulset.yaml
- k8s-deploy/k8s/axon/axon3-statefulset.yaml
- k8s-deploy/k8s/axon/axon4-statefulset.yaml
feat: mount axon data from k8s to volume
> feat: mount axon data from k8s to volume

- k8s-deploy/k8s/axon/deploy.sh
fix: update axon deploy script
> fix: update axon deploy script

- k8s-deploy/k8s/axon/axon1-statefulset.yaml
- k8s-deploy/k8s/axon/axon2-statefulset.yaml
- k8s-deploy/k8s/axon/axon3-statefulset.yaml
- k8s-deploy/k8s/axon/axon4-statefulset.yaml
> feat(k8s): update axon1-statefulset.yaml

- README.md
- pr-bot/README.md
- pr-bot/src/repo/repo_info.js
- pr-bot/yarn.lock
> feat(pr-bot): ignore draft pr

- axon-nginx/README.md
- axon-nginx/nginx/conf.d/axon.conf
- axon-nginx/nginx/conf/nginx.conf
> fix: enable niginx keepalive

- k8s-deploy/k8s/axon/axon-config/node_1.toml
- k8s-deploy/k8s/axon/axon-config/node_2.toml
- k8s-deploy/k8s/axon/axon-config/node_3.toml
- k8s-deploy/k8s/axon/axon-config/node_4.toml
fix: updated tracing address to local
> fix: updated tracing address to local

- deploy/templates/config.toml
- k8s-deploy/devtools/chain/node_1.toml
- k8s-deploy/devtools/chain/node_2.toml
- k8s-deploy/devtools/chain/node_3.toml
- k8s-deploy/devtools/chain/node_4.toml
- k8s-deploy/k8s/axon/axon-config/node_1.toml
- k8s-deploy/k8s/axon/axon-config/node_2.toml
- k8s-deploy/k8s/axon/axon-config/node_3.toml
- k8s-deploy/k8s/axon/axon-config/node_4.toml
feat: updated config.toml to latest
> feat: updated config.toml to latest

- benchmark/benchmark/src/contract_benchmark.js
> fix: fix contract benchmark

- axon-nginx/Makefile
- axon-nginx/README.md
- axon-nginx/ansible.cfg
- axon-nginx/config.yml
- axon-nginx/deploy.yml
> feat: refine nginx deploy

- deploy/README.md
> feat: add README for deploy

- deploy/templates/config.toml
- deploy/templates/default.db-options
> fix: update rocksdb config

- deploy/templates/config.toml
- k8s-deploy/k8s/axon/axon-config/default.db-options
- k8s-deploy/k8s/axon/axon-config/node_1.toml
- k8s-deploy/k8s/axon/axon-config/node_2.toml
- k8s-deploy/k8s/axon/axon-config/node_3.toml
- k8s-deploy/k8s/axon/axon-config/node_4.toml
- k8s-deploy/k8s/axon/axon1-statefulset.yaml
- k8s-deploy/k8s/axon/axon2-statefulset.yaml
- k8s-deploy/k8s/axon/axon3-statefulset.yaml
- k8s-deploy/k8s/axon/axon4-statefulset.yaml
- k8s-deploy/k8s/axon/deploy.sh
> fix: update k8s deploy config

- k8s-deploy/README.md
feat: add readme for k8s deploy
> feat: add readme for k8s deploy

- README.md
- deploy/Makefile
- deploy/README.md
> feat(deploy): add check command

- benchmark/benchmark/Dockerfile
fix: update benchmark working dir
> fix: update benchmark working dir

- apm/monitor/config/grafana/dashboards/axon-benchmark.json
- apm/monitor/config/grafana/provisioning/datasources/datasources.yaml
fix: update grafana datasource
> fix: update grafana datasource

- k8s-deploy/README.md
fix: update readme for k8s deploy
> fix: update readme for k8s deploy

- benchmark/benchmark/package.json
- benchmark/benchmark/src/benchmark.js
- benchmark/benchmark/src/logger.js
- benchmark/benchmark/yarn.lock
> fix(logger): no such file or directory

- apm/monitor/config/grafana/dashboards/axon-benchmark.json
> fix: update jemalloc panels

- benchmark/benchmark/config.json
- benchmark/benchmark/index.js
- benchmark/benchmark/package.json
- benchmark/benchmark/src/account_factory.js
- benchmark/benchmark/src/runner.js
- benchmark/benchmark/yarn.lock
> feat(benchmark): support mnemonic

- benchmark/benchmark/src/account_factory.js
> feat(benchmark): Lazy start benchmark

- benchmark/benchmark/src/account_factory.js
> feat(benchmark): adjust the initial amount of the account

- benchmark/benchmark/src/runner.js
> fix(benchmark): waiting for the case

- benchmark/benchmark/src/account_factory.js
> feat(benchmark): retry account initialization

- apm/monitor/config/grafana/provisioning/datasources/datasources.yaml
- axon-cli/apm/monitor/config/grafana/grafana.ini
- k8s-deploy/README.md
- k8s-deploy/k8s/benchmark/configmap/config.json
- pr-bot/README.md
- pr-bot/config.json
> fix: update es datasource

- benchmark/benchmark/src/account_factory.js
- benchmark/benchmark/src/benchmark.js
- benchmark/benchmark/src/contract_benchmark.js
- benchmark/benchmark/src/runner.js
> feat(benchmark): adapt to the new mem pool

- benchmark/benchmark/src/account_factory.js
- benchmark/benchmark/src/benchmark.js
- benchmark/benchmark/src/runner.js
> feat(benchmark): adapt to the new mem pool 2

- benchmark/benchmark/src/account_factory.js
- benchmark/benchmark/src/benchmark.js
- benchmark/benchmark/src/runner.js
> fix(benchmark): fix nonce

- benchmark/benchmark/config.json
- benchmark/benchmark/index.js
> fix(benchmark): multi node support

- benchmark/benchmark/src/contract_benchmark.js
> feat(benchmarrk): contract support

- benchmark/deploy/deploy.yml
- benchmark/deploy/node_batchsize_threadnum.yml
- benchmark/deploy/templates/config.json
> fix: update benchmark script

- benchmark/benchmark/src/account_factory.js
- benchmark/benchmark/src/benchmark.js
- benchmark/benchmark/src/contract_benchmark.js
- benchmark/benchmark/src/runner.js
> feat(benchmark): unit modification

- benchmark/benchmark/src/contract_benchmark.js
> fix(benchmark): banlance

- benchmark/benchmark/src/contract_benchmark.js
> fix(benchmark): fix gas

- benchmark/benchmark/src/contract_benchmark.js
> fix(benchmark): fix balance

- axon-cli/devtools/config/genesis_four_nodes.json
- axon-cli/devtools/config/genesis_single_node.json
- deploy/templates/genesis.json
- docker-deploy/templates/genesis.json
- k8s-deploy/k8s/axon/axon-config/genesis.json
> feat: update chain_id from 5 to 2022

- benchmark/benchmark/src/account_factory.js
> fix(benchmark): account creation timeout

- benchmark/benchmark/config.json
- benchmark/benchmark/index.js
- benchmark/benchmark/src/account_factory.js
- benchmark/benchmark/src/benchmark.js
- benchmark/benchmark/src/contract_benchmark.js
> feat(benchmark): use chain_id as a configuration

- apm/docs/monitor-deploy.md
- axon-faucet/README.md
- axon-faucet/config.yml
- axon-image/config.yml
- deploy/README.md
- deploy/config.yml
- docker-deploy/config.yml
- k8s-deploy/README.md
- pr-bot/README.md
- pr-bot/config.json
> fix: update orgs name

- benchmark/deploy/config.yml
- benchmark/deploy/deploy.yml
- benchmark/deploy/docker-compose.yml
- benchmark/deploy/templates/config.json
feat: update benchamrk configs
> feat: update benchamrk configs

- benchmark/README.md
> docs: update benchmark docs

- axon-nginx/Makefile
- axon-nginx/README.md
- axon-nginx/config.yml
- axon-nginx/deploy.yml
- axon-nginx/docker-compose.yml
- axon-nginx/nginx/conf/nginx.conf
Add json format output log, print rpc method
Remove deploy_path, nginx-deploy is not like faucet and explorer to pull source code, the current directory is the deployment directory, deploy_path is not used
> refactor: Update nginx deploy
